#!/bin/bash
# Copyright 2007-2008 Mike Kelly <pioto@pioto.org>
# Released under the terms of the GNU General Public License v2
#
# Based upon a script from: http://www.disciplina.net/howto/initscript
#
# Modified by Greg Fitzgerald <netzdamon@gmail.com>

# Basic configuration
PATH="/bin:/sbin:/usr/bin:/usr/sbin"
root="/dev/mapper/Betsy-root"
key_drive="/dev/sdc1"
key_location="/mnt"
#key_name="key.gpg" #obsolete
init="/sbin/init"
#debug=false # not used yet
modules="dm-crypt dm-mod serpent sha256 blowfish" #Any modules you might need to load

# Include our functions
. /scripts/functions.sh

mount -n -t proc none /proc
mount -n -t sysfs none /sys

CMDLINE=`cat /proc/cmdline`

for param in $CMDLINE ; do
	case "$param" in
		root=*|init=*)
			eval "$param"
		;;
		rescue)
			rescue="y"
		;;
        drive*)
            DRIVES+=(${param##*=})
		;;
	esac
done

if [ -z "$root" ]; then
    eerror "No root filesystem specified"
    eerror "Please append a correct \"root=\" boot option"
    eerror "Dropping you to a limited shell."
    eerror "press CTRL-ALT-Del for reboot"
    exec /bin/sh 
fi

#Disable kernel messages from popping onto the screen
echo 0 > /proc/sys/kernel/printk

#Clear the screen
clear

einfo "Initramfs booting..."

# populate /dev with meaningful stuff
einfo "Scanning for device nodes..."
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

# Load modules if you are using them.
einfo "Loading any necessary modules."
for i in $modules;
do 
    modprobe $i >/dev/null 2>&1
done

# raid
#mdadm --assemble /dev/md2 /dev/sda2 /dev/sdb2

waitfor_drives /dev/sdc1 /dev/sda2 /dev/sdb1

# Mount our usb key drive
einfo "Mounting key drive..."
if [ -b "${key_drive}" ]
then
    mount -o ro $key_drive $key_location 
else
    askfor_key
fi

#if $debug; then
    #einfo "Testing key drive..."
    ## Make a real test this is going to pass either way since /usb is already
    ## created.
    #touch /usb/it_got_mounted || eerror "unable to write to usb key, not being mounted"
#fi

# now, we decrypt our lvm pv
decrypt_drives

einfo "Finding lvm devices..."
/sbin/vgscan --mknodes
einfo "Activating lvm devices..."
/sbin/vgchange -a y

# Umount key drive
einfo "Ejecting key drive..."
umount -f $key_location

einfo "Mounting root device: $root ..."
mount -n -t ext3 $root /newroot -o ro

if [ -n "$rescue" ]; then
	ewarn "\"rescue\" kernel parameter received."
	ewarn "Going to a rescue shell..."
	exec /bin/sh
fi

# Unset variables incase the init script we pass off to doesn't clear them for
# us.
undo_vars

#Check if $init exists and is executable
if [[ -x "/newroot/${init}" ]] ; then
    einfo "Unmounting /sys and /proc ..."
    umount -f /sys /proc 

    einfo "Changing to $root and handing over to init..."
    exec switch_root -c /dev/console /newroot "$init" "$@"
else
    #This will only be run if the exec above failed
    eerror "Failed to switch_root, dropping to a shell"
    exec /bin/sh
fi

# vim: set ft=sh tw=78:
